#!/usr/bin/env python3
"""
Streaming Demo for PromptPlot v2.0

This example demonstrates real-time streaming G-code generation and execution.
Shows how commands are generated by the LLM and immediately sent to the plotter
for a live drawing experience.

Features:
- Real-time G-code generation
- Live plotter visualization
- Progress monitoring
- Interactive prompts
- Error handling and recovery

Usage:
    python examples/streaming_demo.py --provider ollama
    python examples/streaming_demo.py --provider azure --interactive
    python examples/streaming_demo.py --mock  # Use mock LLM for demo
"""

import asyncio
import sys
import os
import argparse
import time
from pathlib import Path
from typing import List, Optional

# Add the parent directory to the path so we can import promptplot
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from promptplot import SimplePlotterStreamWorkflow, AdvancedPlotterStreamWorkflow
    from promptplot.plotter.simulated import SimulatedPlotter
    from promptplot.llm.providers import OllamaProvider, AzureOpenAIProvider
    from promptplot.config import get_config
    from promptplot.visualization import ProgressMonitor
    from tests.utils.mocks import MockLLMProvider
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Make sure PromptPlot is installed: pip install -e .")
    sys.exit(1)


class StreamingDemo:
    """Interactive streaming demo class."""
    
    def __init__(self, provider_type: str = "mock"):
        self.provider_type = provider_type
        self.llm_provider = None
        self.plotter = None
        self.workflow = None
        self.progress_monitor = ProgressMonitor()
        
    async def setup_llm_provider(self):
        """Set up the LLM provider based on type."""
        print(f"🔧 Setting up {self.provider_type} LLM provider...")
        
        if self.provider_type == "mock":
            # Create mock provider with realistic streaming responses
            streaming_responses = [
                '{"command": "G28", "comment": "Home all axes"}',
                '{"command": "G1", "x": 0.0, "y": 0.0, "z": 5.0, "f": 3000, "comment": "Move to start position"}',
                '{"command": "M3", "s": 255, "comment": "Pen down"}',
                '{"command": "G1", "x": 10.0, "y": 0.0, "f": 1000, "comment": "Draw line 1"}',
                '{"command": "G1", "x": 10.0, "y": 10.0, "f": 1000, "comment": "Draw line 2"}',
                '{"command": "G1", "x": 0.0, "y": 10.0, "f": 1000, "comment": "Draw line 3"}',
                '{"command": "G1", "x": 0.0, "y": 0.0, "f": 1000, "comment": "Draw line 4"}',
                '{"command": "M5", "comment": "Pen up"}',
                '{"command": "G1", "x": 15.0, "y": 5.0, "f": 3000, "comment": "Move to circle center"}',
                '{"command": "M3", "s": 255, "comment": "Pen down"}',
                '{"command": "G2", "x": 15.0, "y": 5.0, "i": 5.0, "j": 0.0, "f": 800, "comment": "Draw circle"}',
                '{"command": "M5", "comment": "Pen up"}',
                '{"command": "G28", "comment": "Return home"}'
            ]
            self.llm_provider = MockLLMProvider(responses=streaming_responses)
            print("✅ Mock LLM provider ready (no API keys needed)")
            
        elif self.provider_type == "ollama":
            try:
                import requests
                response = requests.get("http://localhost:11434/api/tags", timeout=5)
                if response.status_code != 200:
                    raise Exception("Ollama not responding")
                
                models = response.json().get("models", [])
                if not models:
                    raise Exception("No Ollama models available")
                
                model = models[0]["name"]
                self.llm_provider = OllamaProvider(
                    model=model,
                    request_timeout=30000
                )
                print(f"✅ Ollama provider ready with model: {model}")
                
            except Exception as e:
                print(f"❌ Ollama setup failed: {e}")
                print("Please ensure Ollama is running and has models installed")
                return False
                
        elif self.provider_type == "azure":
            required_vars = ["AZURE_OPENAI_API_KEY", "AZURE_OPENAI_ENDPOINT"]
            missing = [var for var in required_vars if not os.getenv(var)]
            
            if missing:
                print(f"❌ Missing Azure credentials: {', '.join(missing)}")
                return False
            
            self.llm_provider = AzureOpenAIProvider(
                model=os.getenv("AZURE_OPENAI_MODEL", "gpt-4o"),
                deployment_name=os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o"),
                api_key=os.getenv("AZURE_OPENAI_API_KEY"),
                azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
                api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-15-preview"),
                timeout=60
            )
            print("✅ Azure OpenAI provider ready")
        
        return True
    
    async def setup_plotter(self):
        """Set up the simulated plotter with visualization."""
        print("🖨️  Setting up simulated plotter...")
        
        self.plotter = SimulatedPlotter(
            port="STREAMING_DEMO",
            visualize=True,
            canvas_size=(100, 100),  # 100x100mm canvas
            show_grid=True,
            real_time_delay=0.5  # Slow down for demo effect
        )
        
        print("✅ Simulated plotter ready with live visualization")
        return True
    
    async def setup_workflow(self, advanced: bool = False):
        """Set up the streaming workflow."""
        config = get_config()
        
        if advanced:
            print("🔄 Setting up advanced streaming workflow...")
            self.workflow = AdvancedPlotterStreamWorkflow(
                llm_provider=self.llm_provider,
                plotter=self.plotter,
                config=config,
                max_steps=20
            )
        else:
            print("🔄 Setting up simple streaming workflow...")
            self.workflow = SimplePlotterStreamWorkflow(
                llm_provider=self.llm_provider,
                plotter=self.plotter,
                config=config
            )
        
        print("✅ Streaming workflow ready")
        return True
    
    async def stream_drawing(self, prompt: str, show_progress: bool = True):
        """Execute streaming drawing with real-time feedback."""
        print(f"\n🎨 Starting streaming drawing: '{prompt}'")
        print("=" * 60)
        
        if show_progress:
            self.progress_monitor.start_monitoring("streaming_demo")
        
        try:
            # Start the workflow
            print("⏳ Initializing workflow...")
            
            # Connect to plotter
            async with self.plotter:
                print("🔗 Connected to plotter")
                
                # Execute streaming workflow
                print("🚀 Starting real-time G-code generation and execution...")
                print("📺 Watch the visualization window for live drawing!")
                print()
                
                start_time = time.time()
                
                # Run the workflow (this will stream commands in real-time)
                result = await self.workflow.run(prompt)
                
                end_time = time.time()
                duration = end_time - start_time
                
                if show_progress:
                    self.progress_monitor.complete_monitoring("streaming_demo")
                
                print(f"\n✅ Streaming completed in {duration:.2f} seconds!")
                
                if hasattr(result, 'commands_executed'):
                    print(f"📊 Commands executed: {result.commands_executed}")
                
                if hasattr(result, 'total_distance'):
                    print(f"📏 Total drawing distance: {result.total_distance:.2f}mm")
                
                return True
                
        except Exception as e:
            print(f"❌ Streaming error: {e}")
            if show_progress:
                self.progress_monitor.complete_monitoring("streaming_demo")
            return False
    
    async def interactive_mode(self):
        """Run interactive streaming mode."""
        print("\n🎮 Interactive Streaming Mode")
        print("=" * 35)
        print("Enter drawing prompts and watch them stream in real-time!")
        print("Commands: 'quit' to exit, 'clear' to clear canvas, 'help' for help")
        print()
        
        while True:
            try:
                prompt = input("🎨 Enter drawing prompt (or 'quit'): ").strip()
                
                if not prompt:
                    continue
                
                if prompt.lower() in ['quit', 'exit', 'q']:
                    print("👋 Goodbye!")
                    break
                
                if prompt.lower() == 'clear':
                    # Reset plotter visualization
                    if hasattr(self.plotter, 'clear_canvas'):
                        self.plotter.clear_canvas()
                    print("🧹 Canvas cleared!")
                    continue
                
                if prompt.lower() == 'help':
                    print("\n📖 Help:")
                    print("• Enter any drawing prompt (e.g., 'draw a star')")
                    print("• Watch the visualization window for real-time drawing")
                    print("• Use 'clear' to reset the canvas")
                    print("• Use 'quit' to exit")
                    print()
                    continue
                
                # Execute the streaming drawing
                success = await self.stream_drawing(prompt, show_progress=False)
                
                if success:
                    print("✨ Drawing completed! Enter another prompt or 'quit'.\n")
                else:
                    print("❌ Drawing failed. Try a different prompt.\n")
                
            except KeyboardInterrupt:
                print("\n👋 Goodbye!")
                break
            except Exception as e:
                print(f"❌ Error: {e}\n")
    
    async def demo_sequence(self):
        """Run a sequence of demo drawings."""
        demo_prompts = [
            "Draw a simple square",
            "Draw a circle next to the square", 
            "Draw a triangle above them",
            "Connect all shapes with lines"
        ]
        
        print("\n🎬 Running demo sequence...")
        print("=" * 30)
        
        for i, prompt in enumerate(demo_prompts, 1):
            print(f"\n📝 Demo {i}/{len(demo_prompts)}: {prompt}")
            
            success = await self.stream_drawing(prompt, show_progress=True)
            
            if not success:
                print(f"❌ Demo {i} failed, continuing...")
            
            # Pause between demos
            if i < len(demo_prompts):
                print("⏸️  Pausing for 2 seconds...")
                await asyncio.sleep(2)
        
        print("\n🎉 Demo sequence completed!")


async def main():
    """Main demo function."""
    parser = argparse.ArgumentParser(description="PromptPlot Streaming Demo")
    parser.add_argument(
        "--provider", 
        choices=["mock", "ollama", "azure"], 
        default="mock",
        help="LLM provider to use (default: mock)"
    )
    parser.add_argument(
        "--interactive", 
        action="store_true",
        help="Run in interactive mode"
    )
    parser.add_argument(
        "--advanced", 
        action="store_true",
        help="Use advanced streaming workflow"
    )
    parser.add_argument(
        "--prompt", 
        help="Single prompt to execute (non-interactive)"
    )
    
    args = parser.parse_args()
    
    print("🌊 PromptPlot v2.0 Streaming Demo")
    print("=" * 40)
    print(f"Provider: {args.provider}")
    print(f"Workflow: {'Advanced' if args.advanced else 'Simple'} Streaming")
    print()
    
    # Create demo instance
    demo = StreamingDemo(args.provider)
    
    # Setup components
    if not await demo.setup_llm_provider():
        return False
    
    if not await demo.setup_plotter():
        return False
    
    if not await demo.setup_workflow(args.advanced):
        return False
    
    print("\n🚀 All systems ready!")
    
    try:
        if args.interactive:
            # Interactive mode
            await demo.interactive_mode()
        elif args.prompt:
            # Single prompt mode
            success = await demo.stream_drawing(args.prompt)
            if success:
                input("\n⏸️  Press Enter to exit...")
            return success
        else:
            # Demo sequence mode
            await demo.demo_sequence()
            input("\n⏸️  Press Enter to exit...")
        
        return True
        
    except KeyboardInterrupt:
        print("\n⏹️  Demo interrupted by user")
        return True
    except Exception as e:
        print(f"\n💥 Demo failed: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    try:
        success = asyncio.run(main())
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"Fatal error: {e}")
        sys.exit(1)